begin;

-- P0 application commands. Opaque tokens are generated by the application
-- server; only their 64-character SHA-256/HMAC digests cross this boundary.

create or replace function private.require_token_hash(p_token_hash text)
returns text
language plpgsql
immutable
set search_path = pg_catalog
as $$
begin
  if p_token_hash is null or p_token_hash !~ '^[a-f0-9]{64}$' then
    raise exception 'invalid token' using errcode = '22023';
  end if;
  return p_token_hash;
end;
$$;

create or replace function public.create_circle(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_circle_id uuid := gen_random_uuid();
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
  v_slug text := lower(trim(p_input->>'slug'));
begin
  if v_actor is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;
  if v_slug !~ '^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$' then
    raise exception 'invalid Circle slug' using errcode = '22023';
  end if;

  v_existing := private.begin_idempotent_operation(
    'create_circle',
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  insert into public.circles(
    id, name, slug, description, general_area, join_policy, created_by
  ) values (
    v_circle_id,
    left(trim(p_input->>'name'), 100),
    v_slug,
    left(coalesce(trim(p_input->>'description'), ''), 1200),
    left(trim(p_input->>'generalArea'), 100),
    coalesce(nullif(p_input->>'joinPolicy', ''), 'invite_only'),
    v_actor
  );

  insert into public.circle_memberships(
    circle_id, profile_id, role, status, joined_at
  ) values (
    v_circle_id, v_actor, 'circle_admin', 'active', timezone('utc', now())
  );

  perform private.record_audit(
    v_circle_id, v_actor, 'circle.created', 'circle', v_circle_id, '{}'::jsonb
  );
  perform private.record_outbox(
    'circle', v_circle_id, 'circle.created',
    jsonb_build_object('circle_id', v_circle_id, 'creator_profile_id', v_actor)
  );
  perform private.complete_idempotent_operation(
    'create_circle', v_key, 201,
    jsonb_build_object('circleId', v_circle_id), v_circle_id
  );
  return v_circle_id;
end;
$$;

create or replace function public.create_circle_invite(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_circle_id uuid := (p_input->>'circleId')::uuid;
  v_invite_id uuid := gen_random_uuid();
  v_expires_at timestamptz := (p_input->>'expiresAt')::timestamptz;
  v_max_uses integer := coalesce((p_input->>'maxUses')::integer, 1);
  v_token_hash text := private.require_token_hash(p_input->>'tokenHash');
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
begin
  if v_actor is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;
  if not public.can_moderate_circle(v_circle_id, v_actor) then
    raise exception 'moderator access required' using errcode = '42501';
  end if;
  if v_expires_at <= timezone('utc', now())
     or v_expires_at > timezone('utc', now()) + interval '30 days' then
    raise exception 'invite expiration is outside the permitted window' using errcode = '22023';
  end if;
  if v_max_uses < 1 or v_max_uses > 250 then
    raise exception 'invalid invite use limit' using errcode = '22023';
  end if;

  v_existing := private.begin_idempotent_operation(
    'create_circle_invite',
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  insert into public.circle_invites(
    id, circle_id, created_by, role, max_uses, expires_at
  ) values (
    v_invite_id, v_circle_id, v_actor, 'member', v_max_uses, v_expires_at
  );
  insert into private.invite_secrets(invite_id, token_hash)
  values (v_invite_id, v_token_hash);

  perform private.record_audit(
    v_circle_id, v_actor, 'invite.created', 'circle_invite', v_invite_id,
    jsonb_build_object('max_uses', v_max_uses, 'expires_at', v_expires_at)
  );
  perform private.complete_idempotent_operation(
    'create_circle_invite', v_key, 201,
    jsonb_build_object('inviteId', v_invite_id), v_invite_id
  );
  return v_invite_id;
end;
$$;

create or replace function public.get_circle_invite_preview(p_token_hash text)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_result jsonb;
begin
  perform private.require_token_hash(p_token_hash);

  select jsonb_build_object(
    'circleName', c.name,
    'generalArea', c.general_area,
    'description', c.description,
    'expiresAt', i.expires_at
  )
  into v_result
  from private.invite_secrets s
  join public.circle_invites i on i.id = s.invite_id
  join public.circles c on c.id = i.circle_id
  where s.token_hash = p_token_hash
    and i.status = 'active'
    and i.expires_at > timezone('utc', now())
    and i.use_count < i.max_uses
    and c.status = 'active';

  return v_result;
exception
  when others then
    return null;
end;
$$;

create or replace function public.accept_circle_invite(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_invite public.circle_invites;
  v_membership_id uuid;
  v_token_hash text := private.require_token_hash(p_input->>'tokenHash');
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
begin
  if v_actor is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;

  select i.*
  into v_invite
  from private.invite_secrets s
  join public.circle_invites i on i.id = s.invite_id
  where s.token_hash = v_token_hash
  for update of i;

  if not found
     or v_invite.status <> 'active'
     or v_invite.expires_at <= timezone('utc', now())
     or v_invite.use_count >= v_invite.max_uses then
    raise exception 'invite is invalid or expired' using errcode = 'P0002';
  end if;

  v_existing := private.begin_idempotent_operation(
    'accept_circle_invite',
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  select id into v_membership_id
  from public.circle_memberships
  where circle_id = v_invite.circle_id and profile_id = v_actor
  for update;

  if found then
    if exists (
      select 1 from public.circle_memberships
      where id = v_membership_id and status in ('suspended','restricted')
    ) then
      raise exception 'membership requires administrator review' using errcode = '42501';
    end if;
    update public.circle_memberships
       set status = 'active',
           joined_at = coalesce(joined_at, timezone('utc', now()))
     where id = v_membership_id;
  else
    insert into public.circle_memberships(
      circle_id, profile_id, role, status, joined_at
    ) values (
      v_invite.circle_id, v_actor, 'member', 'active', timezone('utc', now())
    )
    returning id into v_membership_id;

    update public.circle_invites
       set use_count = use_count + 1,
           status = case
             when use_count + 1 >= max_uses then 'exhausted'::public.invite_status
             else status
           end
     where id = v_invite.id;
  end if;

  perform private.record_audit(
    v_invite.circle_id, v_actor, 'membership.joined', 'circle_membership',
    v_membership_id, jsonb_build_object('invite_id', v_invite.id)
  );
  perform private.record_outbox(
    'membership', v_membership_id, 'membership.joined',
    jsonb_build_object(
      'circle_id', v_invite.circle_id,
      'profile_id', v_actor,
      'membership_id', v_membership_id
    )
  );
  perform private.complete_idempotent_operation(
    'accept_circle_invite', v_key, 200,
    jsonb_build_object(
      'membershipId', v_membership_id,
      'circleId', v_invite.circle_id
    ),
    v_membership_id
  );
  return v_membership_id;
end;
$$;

create or replace function public.publish_ask_with_share(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_ask public.asks;
  v_share_id uuid := gen_random_uuid();
  v_token_hash text := private.require_token_hash(p_input->>'tokenHash');
  v_expires_at timestamptz := (p_input->>'expiresAt')::timestamptz;
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
begin
  select * into v_ask
  from public.asks
  where id = (p_input->>'askId')::uuid
  for update;

  if not found then
    raise exception 'ask not found' using errcode = 'P0002';
  end if;
  if v_ask.created_by <> v_actor then
    raise exception 'only the owner can publish' using errcode = '42501';
  end if;
  if v_ask.status not in ('draft','open','partially_fulfilled','ready') then
    raise exception 'ask cannot be shared in its current state' using errcode = '22023';
  end if;
  if exists (
    select 1 from public.ask_needs
    where ask_id = v_ask.id and risk_level in ('restricted','prohibited')
  ) then
    raise exception 'restricted or prohibited need requires review' using errcode = '42501';
  end if;
  if v_expires_at <= timezone('utc', now())
     or v_expires_at > least(v_ask.expires_at, timezone('utc', now()) + interval '30 days') then
    raise exception 'share expiration is outside the permitted window' using errcode = '22023';
  end if;

  v_existing := private.begin_idempotent_operation(
    'publish_ask_with_share',
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  update private.share_links
     set revoked_at = timezone('utc', now())
   where ask_id = v_ask.id and revoked_at is null;

  update public.asks
     set status = case when status = 'draft' then 'open'::public.ask_status else status end,
         published_at = coalesce(published_at, timezone('utc', now())),
         share_version = share_version + 1
   where id = v_ask.id;

  insert into private.share_links(
    id, ask_id, circle_id, token_hash, expires_at, created_by
  ) values (
    v_share_id, v_ask.id, v_ask.circle_id, v_token_hash, v_expires_at, v_actor
  );

  perform private.record_audit(
    v_ask.circle_id, v_actor, 'ask.published', 'ask', v_ask.id,
    jsonb_build_object('share_link_id', v_share_id)
  );
  perform private.record_outbox(
    'ask', v_ask.id, 'ask.published',
    jsonb_build_object('ask_id', v_ask.id, 'circle_id', v_ask.circle_id)
  );
  perform private.complete_idempotent_operation(
    'publish_ask_with_share', v_key, 201,
    jsonb_build_object('askId', v_ask.id, 'shareLinkId', v_share_id),
    v_share_id
  );
  return v_share_id;
end;
$$;

create or replace function public.get_shared_ask(p_token_hash text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_link private.share_links;
  v_result jsonb;
begin
  perform private.require_token_hash(p_token_hash);

  select * into v_link
  from private.share_links
  where token_hash = p_token_hash
    and revoked_at is null
    and expires_at > timezone('utc', now())
  for update;

  if not found then
    return null;
  end if;

  select jsonb_build_object(
    'askId', a.id,
    'circleName', c.name,
    'circleGeneralArea', c.general_area,
    'title', a.title,
    'description', a.description,
    'generalLocation', a.general_location,
    'neededBy', a.needed_by,
    'expiresAt', least(a.expires_at, v_link.expires_at),
    'status', a.status,
    'coverImagePath', a.cover_image_path,
    'needs', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', n.id,
          'kind', n.kind,
          'title', n.title,
          'description', n.description,
          'quantityRequested', n.quantity_requested,
          'quantityCommitted', n.quantity_committed,
          'unit', n.unit,
          'status', n.status
        )
        order by n.sort_order, n.created_at
      )
      from public.ask_needs n
      where n.ask_id = a.id
        and n.status <> 'cancelled'
        and n.risk_level in ('low','moderate')
    ), '[]'::jsonb)
  )
  into v_result
  from public.asks a
  join public.circles c on c.id = a.circle_id
  where a.id = v_link.ask_id
    and a.circle_id = v_link.circle_id
    and a.status in ('open','partially_fulfilled','ready','in_progress')
    and a.expires_at > timezone('utc', now())
    and c.status = 'active';

  if v_result is not null then
    update private.share_links
       set access_count = access_count + 1,
           last_accessed_at = timezone('utc', now())
     where id = v_link.id;
  end if;

  return v_result;
exception
  when others then
    return null;
end;
$$;

create or replace function public.redeem_shared_ask(p_token_hash text)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_link private.share_links;
begin
  if v_actor is null then
    raise exception 'verification required' using errcode = '28000';
  end if;
  perform private.require_token_hash(p_token_hash);

  select * into v_link
  from private.share_links
  where token_hash = p_token_hash
    and revoked_at is null
    and expires_at > timezone('utc', now())
  for update;

  if not found or not exists (
    select 1 from public.asks a
    where a.id = v_link.ask_id
      and a.status in ('open','partially_fulfilled')
      and a.expires_at > timezone('utc', now())
  ) then
    raise exception 'shared Ask is unavailable' using errcode = 'P0002';
  end if;

  insert into private.ask_guest_grants(
    ask_id, circle_id, profile_id, share_link_id, expires_at
  ) values (
    v_link.ask_id,
    v_link.circle_id,
    v_actor,
    v_link.id,
    least(v_link.expires_at, timezone('utc', now()) + interval '48 hours')
  )
  on conflict (ask_id, profile_id)
  do update set
    share_link_id = excluded.share_link_id,
    status = 'active',
    revoked_at = null,
    expires_at = excluded.expires_at;

  perform private.record_audit(
    v_link.circle_id, v_actor, 'share.guest_redeemed', 'ask', v_link.ask_id,
    jsonb_build_object('share_link_id', v_link.id)
  );
  return v_link.ask_id;
end;
$$;

create or replace function public.decide_offer(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_offer public.offers;
  v_action text := p_input->>'action';
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
  v_status public.offer_status;
begin
  if v_action not in ('decline','withdraw') then
    raise exception 'unsupported Offer decision' using errcode = '22023';
  end if;
  select * into v_offer
  from public.offers
  where id = (p_input->>'offerId')::uuid
  for update;
  if not found then
    raise exception 'Offer not found' using errcode = 'P0002';
  end if;
  if v_offer.status <> 'submitted' then
    return v_offer.id;
  end if;
  if v_action = 'withdraw' and v_offer.contributor_profile_id <> v_actor then
    raise exception 'only the contributor can withdraw' using errcode = '42501';
  end if;
  if v_action = 'decline' and not exists (
    select 1 from public.asks a
    where a.id = v_offer.ask_id and a.created_by = v_actor
  ) then
    raise exception 'only the requester can decline' using errcode = '42501';
  end if;

  v_existing := private.begin_idempotent_operation(
    'decide_offer:' || v_action,
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  v_status := case
    when v_action = 'withdraw' then 'withdrawn'::public.offer_status
    else 'declined'::public.offer_status
  end;
  update public.offers
     set status = v_status,
         withdrawn_at = case when v_action = 'withdraw' then timezone('utc', now()) else withdrawn_at end,
         decided_at = case when v_action = 'decline' then timezone('utc', now()) else decided_at end
   where id = v_offer.id;

  perform private.record_audit(
    v_offer.circle_id, v_actor, 'offer.' || v_action || 'd',
    'offer', v_offer.id, '{}'::jsonb
  );
  perform private.record_outbox(
    'offer', v_offer.id, 'offer.' || v_action || 'd',
    jsonb_build_object('offer_id', v_offer.id, 'ask_id', v_offer.ask_id)
  );
  perform private.complete_idempotent_operation(
    'decide_offer:' || v_action, v_key, 200,
    jsonb_build_object('offerId', v_offer.id, 'status', v_status),
    v_offer.id
  );
  return v_offer.id;
end;
$$;

create or replace function public.transition_ask(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_ask public.asks;
  v_action text := p_input->>'action';
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
  v_status public.ask_status;
begin
  select * into v_ask
  from public.asks
  where id = (p_input->>'askId')::uuid
  for update;
  if not found then
    raise exception 'Ask not found' using errcode = 'P0002';
  end if;
  if v_ask.created_by <> v_actor
     and not public.can_moderate_circle(v_ask.circle_id, v_actor) then
    raise exception 'not authorized' using errcode = '42501';
  end if;
  if v_action not in ('cancel','complete','archive') then
    raise exception 'unsupported Ask transition' using errcode = '22023';
  end if;
  if v_action = 'complete' and exists (
    select 1 from public.loans l
    join public.commitments c on c.id = l.commitment_id
    where c.ask_id = v_ask.id
      and l.status not in ('returned','cancelled')
  ) then
    raise exception 'active custody must be resolved first' using errcode = '22023';
  end if;

  v_existing := private.begin_idempotent_operation(
    'transition_ask:' || v_action,
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  v_status := case v_action
    when 'cancel' then 'cancelled'::public.ask_status
    when 'complete' then 'completed'::public.ask_status
    else 'archived'::public.ask_status
  end;
  update public.asks
     set status = v_status,
         completed_at = case when v_action = 'complete' then timezone('utc', now()) else completed_at end,
         archived_at = case when v_action = 'archive' then timezone('utc', now()) else archived_at end
   where id = v_ask.id;
  if v_action in ('cancel','archive') then
    update private.share_links
       set revoked_at = coalesce(revoked_at, timezone('utc', now()))
     where ask_id = v_ask.id;
  end if;

  perform private.record_audit(
    v_ask.circle_id, v_actor, 'ask.' || v_action || 'd',
    'ask', v_ask.id, '{}'::jsonb
  );
  perform private.record_outbox(
    'ask', v_ask.id, 'ask.' || v_action || 'd',
    jsonb_build_object('ask_id', v_ask.id, 'circle_id', v_ask.circle_id)
  );
  perform private.complete_idempotent_operation(
    'transition_ask:' || v_action, v_key, 200,
    jsonb_build_object('askId', v_ask.id, 'status', v_status), v_ask.id
  );
  return v_ask.id;
end;
$$;

create or replace function public.send_commitment_message(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_commitment public.commitments;
  v_message_id uuid := gen_random_uuid();
  v_body text := trim(p_input->>'body');
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
begin
  select * into v_commitment
  from public.commitments
  where id = (p_input->>'commitmentId')::uuid;
  if not found then
    raise exception 'Commitment not found' using errcode = 'P0002';
  end if;
  if v_actor not in (
    v_commitment.requester_profile_id,
    v_commitment.contributor_profile_id
  ) then
    raise exception 'not a Commitment participant' using errcode = '42501';
  end if;
  if char_length(v_body) < 1 or char_length(v_body) > 4000 then
    raise exception 'invalid message length' using errcode = '22023';
  end if;
  if v_commitment.status in ('cancelled','fulfilled') then
    raise exception 'conversation is closed' using errcode = '22023';
  end if;

  v_existing := private.begin_idempotent_operation(
    'send_commitment_message',
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  insert into public.messages(
    id, circle_id, conversation_id, sender_profile_id, body
  ) values (
    v_message_id, v_commitment.circle_id, v_commitment.conversation_id,
    v_actor, v_body
  );

  perform private.record_outbox(
    'message', v_message_id, 'message.sent',
    jsonb_build_object(
      'message_id', v_message_id,
      'commitment_id', v_commitment.id,
      'conversation_id', v_commitment.conversation_id,
      'sender_profile_id', v_actor
    )
  );
  perform private.complete_idempotent_operation(
    'send_commitment_message', v_key, 201,
    jsonb_build_object('messageId', v_message_id), v_message_id
  );
  return v_message_id;
end;
$$;

create or replace function public.save_resource_from_loan(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_loan public.loans;
  v_commitment public.commitments;
  v_resource_id uuid := gen_random_uuid();
  v_existing_resource_id uuid;
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
begin
  select * into v_loan
  from public.loans
  where id = (p_input->>'sourceLoanId')::uuid
  for share;
  if not found then
    raise exception 'Loan not found' using errcode = 'P0002';
  end if;
  if v_loan.lender_profile_id <> v_actor or v_loan.status <> 'returned' then
    raise exception 'only the lender can remember a returned item' using errcode = '42501';
  end if;
  select * into v_commitment from public.commitments where id = v_loan.commitment_id;

  select id into v_existing_resource_id
  from public.resources
  where source_loan_id = v_loan.id and owner_profile_id = v_actor
  limit 1;
  if v_existing_resource_id is not null then
    return v_existing_resource_id;
  end if;

  v_existing := private.begin_idempotent_operation(
    'save_resource_from_loan',
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  insert into public.resources(
    id, circle_id, owner_profile_id, title, description, category_id,
    visibility, willingness, source_offer_id, source_loan_id, last_confirmed_at
  ) values (
    v_resource_id,
    v_loan.circle_id,
    v_actor,
    left(trim(p_input->>'title'), 100),
    left(coalesce(trim(p_input->>'description'), ''), 800),
    nullif(p_input->>'categoryId', '')::uuid,
    coalesce(nullif(p_input->>'visibility', '')::public.resource_visibility, 'match_only'),
    coalesce(nullif(p_input->>'willingness', '')::public.resource_willingness, 'happy_to_be_asked'),
    v_commitment.offer_id,
    v_loan.id,
    timezone('utc', now())
  );

  perform private.record_audit(
    v_loan.circle_id, v_actor, 'resource.remembered',
    'resource', v_resource_id, jsonb_build_object('loan_id', v_loan.id)
  );
  perform private.complete_idempotent_operation(
    'save_resource_from_loan', v_key, 201,
    jsonb_build_object('resourceId', v_resource_id), v_resource_id
  );
  return v_resource_id;
end;
$$;

create or replace function public.report_incident(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_circle_id uuid := (p_input->>'circleId')::uuid;
  v_incident_id uuid := gen_random_uuid();
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
begin
  if v_actor is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;
  if not public.can_read_circle(v_circle_id, v_actor)
     and not exists (
       select 1 from public.commitments c
       where c.circle_id = v_circle_id
         and v_actor in (c.requester_profile_id, c.contributor_profile_id)
         and (
           c.id = nullif(p_input->>'commitmentId', '')::uuid
           or c.ask_id = nullif(p_input->>'askId', '')::uuid
         )
     ) then
    raise exception 'not authorized to report in this Circle' using errcode = '42501';
  end if;

  v_existing := private.begin_idempotent_operation(
    'report_incident',
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  insert into public.incidents(
    id, circle_id, reported_by, subject_profile_id, ask_id, commitment_id,
    loan_id, kind, summary
  ) values (
    v_incident_id,
    v_circle_id,
    v_actor,
    nullif(p_input->>'subjectProfileId', '')::uuid,
    nullif(p_input->>'askId', '')::uuid,
    nullif(p_input->>'commitmentId', '')::uuid,
    nullif(p_input->>'loanId', '')::uuid,
    (p_input->>'kind')::public.incident_kind,
    left(trim(p_input->>'summary'), 2000)
  );

  perform private.record_audit(
    v_circle_id, v_actor, 'incident.reported',
    'incident', v_incident_id,
    jsonb_build_object('kind', p_input->>'kind')
  );
  perform private.record_outbox(
    'incident', v_incident_id, 'incident.reported',
    jsonb_build_object('incident_id', v_incident_id, 'circle_id', v_circle_id)
  );
  perform private.complete_idempotent_operation(
    'report_incident', v_key, 201,
    jsonb_build_object('incidentId', v_incident_id), v_incident_id
  );
  return v_incident_id;
end;
$$;

create or replace function public.moderate_membership(p_input jsonb)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, public, private
as $$
declare
  v_actor uuid := auth.uid();
  v_membership public.circle_memberships;
  v_action text := p_input->>'action';
  v_key text := p_input->>'idempotencyKey';
  v_existing private.idempotency_records;
begin
  select * into v_membership
  from public.circle_memberships
  where id = (p_input->>'membershipId')::uuid
  for update;
  if not found then
    raise exception 'membership not found' using errcode = 'P0002';
  end if;
  if v_membership.profile_id = v_actor then
    raise exception 'administrators cannot moderate themselves' using errcode = '42501';
  end if;
  if not public.can_moderate_circle(v_membership.circle_id, v_actor) then
    raise exception 'moderator access required' using errcode = '42501';
  end if;
  if v_membership.role = 'circle_admin'
     and not exists (
       select 1 from public.circle_memberships m
       where m.circle_id = v_membership.circle_id
         and m.profile_id = v_actor
         and m.role = 'circle_admin'
         and m.status = 'active'
     ) then
    raise exception 'only a Circle administrator can moderate another administrator' using errcode = '42501';
  end if;
  if v_action not in ('activate','restrict','suspend','restore') then
    raise exception 'unsupported membership action' using errcode = '22023';
  end if;

  v_existing := private.begin_idempotent_operation(
    'moderate_membership:' || v_action,
    v_key,
    encode(extensions.digest(p_input::text, 'sha256'), 'hex')
  );
  if v_existing.completed_at is not null then
    return v_existing.resource_id;
  end if;

  update public.circle_memberships
     set status = case
           when v_action in ('activate','restore') then 'active'::public.membership_status
           when v_action = 'restrict' then 'restricted'::public.membership_status
           else 'suspended'::public.membership_status
         end,
         joined_at = case
           when v_action in ('activate','restore') then coalesce(joined_at, timezone('utc', now()))
           else joined_at
         end,
         restricted_at = case
           when v_action = 'restrict' then timezone('utc', now())
           when v_action in ('activate','restore') then null
           else restricted_at
         end,
         suspended_at = case
           when v_action = 'suspend' then timezone('utc', now())
           when v_action in ('activate','restore') then null
           else suspended_at
         end
   where id = v_membership.id;

  perform private.record_audit(
    v_membership.circle_id, v_actor, 'membership.' || v_action || 'd',
    'circle_membership', v_membership.id,
    jsonb_build_object('target_profile_id', v_membership.profile_id)
  );
  perform private.record_outbox(
    'membership', v_membership.id, 'membership.' || v_action || 'd',
    jsonb_build_object(
      'membership_id', v_membership.id,
      'profile_id', v_membership.profile_id,
      'circle_id', v_membership.circle_id
    )
  );
  perform private.complete_idempotent_operation(
    'moderate_membership:' || v_action, v_key, 200,
    jsonb_build_object('membershipId', v_membership.id), v_membership.id
  );
  return v_membership.id;
end;
$$;

revoke all on function private.require_token_hash(text) from public;

revoke all on function public.create_circle(jsonb) from public;
revoke all on function public.create_circle_invite(jsonb) from public;
revoke all on function public.get_circle_invite_preview(text) from public;
revoke all on function public.accept_circle_invite(jsonb) from public;
revoke all on function public.publish_ask_with_share(jsonb) from public;
revoke all on function public.get_shared_ask(text) from public;
revoke all on function public.redeem_shared_ask(text) from public;
revoke all on function public.decide_offer(jsonb) from public;
revoke all on function public.transition_ask(jsonb) from public;
revoke all on function public.send_commitment_message(jsonb) from public;
revoke all on function public.save_resource_from_loan(jsonb) from public;
revoke all on function public.report_incident(jsonb) from public;
revoke all on function public.moderate_membership(jsonb) from public;

grant execute on function public.get_circle_invite_preview(text) to anon, authenticated;
grant execute on function public.get_shared_ask(text) to anon, authenticated;

grant execute on function public.create_circle(jsonb) to authenticated;
grant execute on function public.create_circle_invite(jsonb) to authenticated;
grant execute on function public.accept_circle_invite(jsonb) to authenticated;
grant execute on function public.publish_ask_with_share(jsonb) to authenticated;
grant execute on function public.redeem_shared_ask(text) to authenticated;
grant execute on function public.decide_offer(jsonb) to authenticated;
grant execute on function public.transition_ask(jsonb) to authenticated;
grant execute on function public.send_commitment_message(jsonb) to authenticated;
grant execute on function public.save_resource_from_loan(jsonb) to authenticated;
grant execute on function public.report_incident(jsonb) to authenticated;
grant execute on function public.moderate_membership(jsonb) to authenticated;

commit;
