export type ServiceDirectoryEntry = {
  id: string;
  category: string;
  categorySlug: string;
  vendor: string;
  contact?: string;
  validationCount: number;
  confidence: "high" | "medium" | "low";
  notes: string;
  sourceMessageIds: string[];
};

export const paseosServiceDirectoryEntries: ServiceDirectoryEntry[] = [
  {
    id: "gerardo-remodel-painting",
    category: "Remodel, ceilings, painting",
    categorySlug: "home-projects",
    vendor: "Gerardo / Geraldo",
    contact: "+1 (561) 698-4834",
    validationCount: 4,
    confidence: "high",
    notes:
      "Repeatedly recommended for bathroom remodels, popcorn removal, skim coating, interior/exterior painting, drywall, and tile crews.",
    sourceMessageIds: ["5043", "7292", "4376", "2638", "1373"],
  },
  {
    id: "romeo-landscaping",
    category: "Landscaping",
    categorySlug: "outdoor",
    vendor: "Romeo",
    contact: "+1 (561) 331-7304",
    validationCount: 4,
    confidence: "high",
    notes:
      "Multiple neighbors called him amazing/the best; used by multiple households and reportedly other Paseos neighbors.",
    sourceMessageIds: ["4106", "4223", "4342", "4095"],
  },
  {
    id: "razorback-electricians",
    category: "Electrical",
    categorySlug: "home-projects",
    vendor: "Razorback Electricians",
    validationCount: 2,
    confidence: "high",
    notes:
      "Recommended twice; one neighbor said they used Razorback for years and love them.",
    sourceMessageIds: ["7875", "3179"],
  },
  {
    id: "little-bird-pool",
    category: "Pool service",
    categorySlug: "outdoor",
    vendor: "Little Bird",
    contact: "Alessandra was named as the main contact",
    validationCount: 2,
    confidence: "medium",
    notes:
      "Weekly pool service mentioned. One neighbor cited $135 monthly for a difficult pool.",
    sourceMessageIds: ["8820"],
  },
  {
    id: "snipedy-do-dah",
    category: "Kids haircuts",
    categorySlug: "family",
    vendor: "Snipedy Do Dah",
    validationCount: 2,
    confidence: "medium",
    notes:
      "Two neighbors recommended it for boys' haircuts; one said they keep returning after trying several places.",
    sourceMessageIds: ["840", "1119"],
  },
  {
    id: "siw-impact-windows",
    category: "Impact windows",
    categorySlug: "home-projects",
    vendor: "SIW Impact Windows",
    contact: "https://www.siwsolutions.com/",
    validationCount: 1,
    confidence: "medium",
    notes:
      "Neighbor worked with them a few years back for a garage door/window and said they were pretty good.",
    sourceMessageIds: ["4545"],
  },
  {
    id: "my-safe-florida-home",
    category: "Grant resource",
    categorySlug: "home-projects",
    vendor: "My Safe Florida Home",
    contact: "https://mysafeflhome.com/grant-application-home-launch/",
    validationCount: 1,
    confidence: "medium",
    notes:
      "Grant resource for windows, doors, and roof projects. Not a contractor.",
    sourceMessageIds: ["8293"],
  },
  {
    id: "paver-man",
    category: "Artificial turf",
    categorySlug: "outdoor",
    vendor: "Paver Man",
    validationCount: 1,
    confidence: "medium",
    notes: "Recommended for backyard turf.",
    sourceMessageIds: ["6439"],
  },
  {
    id: "south-florida-putting-green",
    category: "Artificial turf",
    categorySlug: "outdoor",
    vendor: "South Florida Putting Green",
    validationCount: 1,
    confidence: "medium",
    notes: "Recommended for artificial turf.",
    sourceMessageIds: ["6695"],
  },
  {
    id: "playgrounds-and-turf",
    category: "Artificial turf",
    categorySlug: "outdoor",
    vendor: "Playgrounds and Turf",
    contact: "https://www.playgroundsandturf.com/",
    validationCount: 1,
    confidence: "medium",
    notes: "Neighbor said to ask for JP.",
    sourceMessageIds: ["7080"],
  },
  {
    id: "handy-beet",
    category: "Handyman",
    categorySlug: "home-projects",
    vendor: "Vlad / Handy Beet",
    validationCount: 1,
    confidence: "medium",
    notes: "Recommended for small projects around the house.",
    sourceMessageIds: ["8624"],
  },
  {
    id: "island-air-conditioning",
    category: "A/C and HVAC",
    categorySlug: "home-projects",
    vendor: "Island Air Conditioning",
    validationCount: 1,
    confidence: "medium",
    notes: "Used by a neighbor for A/C replacement quotes.",
    sourceMessageIds: ["6638"],
  },
  {
    id: "lindstrom-hvac",
    category: "A/C and HVAC",
    categorySlug: "home-projects",
    vendor: "Lindstrom",
    validationCount: 1,
    confidence: "medium",
    notes: "Used by a neighbor for A/C replacement quotes.",
    sourceMessageIds: ["6638"],
  },
  {
    id: "modern-ac",
    category: "A/C and HVAC",
    categorySlug: "home-projects",
    vendor: "Scott from Modern AC",
    validationCount: 1,
    confidence: "medium",
    notes: "Neighbor said Scott has always been fair with pricing.",
    sourceMessageIds: ["4669"],
  },
  {
    id: "certapro-cynthia",
    category: "Exterior painting",
    categorySlug: "home-projects",
    vendor: "Cynthia at Certapro",
    contact: "561-237-2742",
    validationCount: 1,
    confidence: "medium",
    notes: "Used for exterior painting; described as fast and reasonable.",
    sourceMessageIds: ["1373"],
  },
  {
    id: "oscar-painting",
    category: "Interior painting",
    categorySlug: "home-projects",
    vendor: "Oscar",
    validationCount: 1,
    confidence: "medium",
    notes: "Described as top quality, but not the cheapest.",
    sourceMessageIds: ["2382"],
  },
  {
    id: "juliano-pool-leak",
    category: "Pool leak detection",
    categorySlug: "outdoor",
    vendor: "Juliano",
    contact: "+1 (954) 854-8067",
    validationCount: 1,
    confidence: "medium",
    notes: "Used for quote and repair.",
    sourceMessageIds: ["5102"],
  },
  {
    id: "marcus-plumber",
    category: "Plumbing",
    categorySlug: "home-projects",
    vendor: "Marcus",
    contact: "+1 (954) 934-8825",
    validationCount: 1,
    confidence: "medium",
    notes: "Suggested for small plumbing jobs.",
    sourceMessageIds: ["6149"],
  },
  {
    id: "david-plumber",
    category: "Plumbing",
    categorySlug: "home-projects",
    vendor: "David",
    validationCount: 1,
    confidence: "low",
    notes:
      "Neighbor said they used David for years, but no contact was included in the public text.",
    sourceMessageIds: ["5770"],
  },
  {
    id: "pool-fence-co",
    category: "Screen repair",
    categorySlug: "home-projects",
    vendor: "Pool Fence Co",
    contact: "https://www.instagram.com/poolfenceco?igsh=bWJvbXBuZ3I4dmZ2",
    validationCount: 0.5,
    confidence: "low",
    notes:
      "Possible lead. Recommender knows the family but had not used the service.",
    sourceMessageIds: ["2182", "2697"],
  },
  {
    id: "blue-shield-pressure-washing",
    category: "Pressure washing",
    categorySlug: "outdoor",
    vendor: "Blue Shield",
    validationCount: 1,
    confidence: "medium",
    notes: "Neighbor likes them and said they do roofs.",
    sourceMessageIds: ["2951"],
  },
  {
    id: "homesmiles-burke",
    category: "Pressure washing",
    categorySlug: "outdoor",
    vendor: "Burke Bagwell / Homesmiles",
    contact: "561-225-5434, bbagwell@homesmiles.com",
    validationCount: 1,
    confidence: "medium",
    notes: "Recommended as a second option.",
    sourceMessageIds: ["2995"],
  },
  {
    id: "squeegee-wizards",
    category: "Pressure washing",
    categorySlug: "outdoor",
    vendor: "Squeegee Wizards",
    validationCount: 1,
    confidence: "medium",
    notes: "Neighbor said they use them.",
    sourceMessageIds: ["3132"],
  },
  {
    id: "altier-jeweler",
    category: "Jeweler",
    categorySlug: "local-services",
    vendor: "Altier Jeweler",
    validationCount: 1,
    confidence: "medium",
    notes: "East Boca on Federal; recommended for repairs.",
    sourceMessageIds: ["8432"],
  },
  {
    id: "international-jewelers-exchange",
    category: "Jeweler",
    categorySlug: "local-services",
    vendor: "International Jewelers Exchange",
    contact: "Glades location",
    validationCount: 1,
    confidence: "medium",
    notes: "Neighbor said they like it.",
    sourceMessageIds: ["7157"],
  },
  {
    id: "iberjoya",
    category: "Jeweler",
    categorySlug: "local-services",
    vendor: "Iberjoya",
    validationCount: 1,
    confidence: "medium",
    notes: "Neighbor said they make all their jewelry and are amazing.",
    sourceMessageIds: ["7295"],
  },
  {
    id: "aletto-jewelers",
    category: "Jeweler",
    categorySlug: "local-services",
    vendor: "Aletto Jewelers",
    contact: "Powerline and Palmetto plaza",
    validationCount: 1,
    confidence: "medium",
    notes: "Family-owned, father and son operated.",
    sourceMessageIds: ["7429"],
  },
  {
    id: "vacations-by-christina",
    category: "Travel agent",
    categorySlug: "local-services",
    vendor: "Christina / Vacations by Christina",
    contact: "https://vacationsbychristina.tpi-independent.com/",
    validationCount: 1,
    confidence: "medium",
    notes:
      "Recommended for summer vacation planning, especially Disney trips.",
    sourceMessageIds: ["5441"],
  },
  {
    id: "sarah-babysitter",
    category: "Babysitter",
    categorySlug: "family",
    vendor: "Sarah",
    contact: "Contact via parent in the group",
    validationCount: 2,
    confidence: "medium",
    notes:
      "Promoted as a babysitter, mother's helper, and pet sitter; later suggested for last-minute help.",
    sourceMessageIds: ["8637", "7452"],
  },
  {
    id: "sami-babysitter",
    category: "Babysitter",
    categorySlug: "family",
    vendor: "Sami",
    contact: "Contact shared privately",
    validationCount: 1,
    confidence: "medium",
    notes:
      "College student studying healthcare; babysits for families with young children.",
    sourceMessageIds: ["4474"],
  },
  {
    id: "shelane-mascaro-babysitter",
    category: "Babysitter",
    categorySlug: "family",
    vendor: "Shelane Mascaro",
    validationCount: 1,
    confidence: "low",
    notes: "Suggested as a possible college-aged babysitter lead.",
    sourceMessageIds: ["4360"],
  },
  {
    id: "cleaning-business",
    category: "Cleaning",
    categorySlug: "home-projects",
    vendor: "Friend's cleaning business",
    contact: "Contact not in public text",
    validationCount: 1,
    confidence: "low",
    notes: "Neighbor said their friend is very good and looking for clients.",
    sourceMessageIds: ["5771"],
  },
  {
    id: "angelcare",
    category: "Home health aide",
    categorySlug: "care",
    vendor: "AngelCare",
    validationCount: 1,
    confidence: "medium",
    notes: "Suggested after a doctor's recommendation.",
    sourceMessageIds: ["7317"],
  },
  {
    id: "cisco-mechanic",
    category: "Mechanic",
    categorySlug: "local-services",
    vendor: "Cisco Mechanic / owner David",
    contact: "East Boca",
    validationCount: 1,
    confidence: "medium",
    notes:
      "Neighbor loves them and said they worked on a BMW.",
    sourceMessageIds: ["7012"],
  },
  {
    id: "pawmper-fluffy",
    category: "Dog grooming",
    categorySlug: "pets",
    vendor: "Pawmper Fluffy Mobile Grooming",
    validationCount: 1,
    confidence: "medium",
    notes:
      "Used for over a year with good experience; another neighbor may also use them.",
    sourceMessageIds: ["5938"],
  },
  {
    id: "paw-depot",
    category: "Dog grooming",
    categorySlug: "pets",
    vendor: "Paw Depot",
    validationCount: 1,
    confidence: "medium",
    notes: "Highly recommended with complimentary pickup and dropoff.",
    sourceMessageIds: ["5549"],
  },
  {
    id: "paws-in-delray",
    category: "Vet",
    categorySlug: "pets",
    vendor: "Paws in Delray",
    validationCount: 1,
    confidence: "medium",
    notes:
      "Neighbor said a good friend opened it and is caring and wonderful.",
    sourceMessageIds: ["6028"],
  },
  {
    id: "we-rock-the-spectrum",
    category: "Kids camp",
    categorySlug: "family",
    vendor: "We Rock the Spectrum",
    validationCount: 1,
    confidence: "medium",
    notes: "Used by a neighbor's child.",
    sourceMessageIds: ["5808"],
  },
  {
    id: "the-little-gym",
    category: "Kids camp",
    categorySlug: "family",
    vendor: "The Little Gym",
    validationCount: 1,
    confidence: "medium",
    notes: "Suggested for winter break camp.",
    sourceMessageIds: ["8921"],
  },
];

export const serviceDirectoryCategories = [
  { slug: "home-projects", label: "Home projects" },
  { slug: "outdoor", label: "Outdoor & pool" },
  { slug: "family", label: "Kids & family" },
  { slug: "pets", label: "Pets" },
  { slug: "local-services", label: "Local services" },
  { slug: "care", label: "Care" },
] as const;
